# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  fetchDepth: 0

- bash: |
    git push --prune https://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@github.com/shabilmuhammed/unittesting.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')